import 'package:flutter/material.dart';
class currency_code_to_currency_symbol extends StatefulWidget {
  final String currencyCode;
  const currency_code_to_currency_symbol({Key? key,required this.currencyCode}):super(key: key);

  @override
  State<currency_code_to_currency_symbol> createState() => _currency_code_to_currency_symbolState();
}

class _currency_code_to_currency_symbolState extends State<currency_code_to_currency_symbol> {
  @override
  Widget build(BuildContext context) {
    return Text(
      getCurrencySymbol(widget.currencyCode)
    );
  }
}
  String getCurrencySymbol(String currencyCode) {
    final upperCaseCurrencyCode = currencyCode.toUpperCase();
    final currencySymbols = {
      'AED': 'د.إ',
      'AFN': '؋',
      'ALL': 'L',
      'AMD': '֏',
      'ANG': 'ƒ',
      'AOA': 'Kz',
      'ARS': '\$',
      'AUD': '\$',
      'AWG': 'ƒ',
      'AZN': '₼',
      'BAM': 'КМ',
      'BBD': '\$',
      'BDT': '৳',
      'BGN': 'лв',
      'BHD': '.د.ب',
      'BIF': 'FBu',
      'BMD': '\$',
      'BND': '\$',
      'BOB': 'Bs.',
      'BRL': 'R\$',
      'BSD': '\$',
      'BTN': 'Nu.',
      'BWP': 'P',
      'BYN': 'Br',
      'BZD': 'BZ\$',
      'CAD': '\$',
      'CDF': 'FC',
      'CHF': 'CHF',
      'CLP': '\$',
      'CNY': '¥',
      'COP': '\$',
      'CRC': '₡',
      'CUP': '\$MN',
      'CVE': '\$',
      'CZK': 'Kč',
      'DJF': 'Fdj',
      'DKK': 'kr',
      'DOP': 'RD\$',
      'DZD': 'دج',
      'EGP': 'ج.م',
      'ERN': 'Nfk',
      'ETB': 'Br',
      'EUR': '€',
      'FJD': '\$',
      'FKP': '£',
      'FOK': 'kr',
      'GBP': '£',
      'GEL': 'ლ',
      'GGP': '£',
      'GHS': '₵',
      'GIP': '£',
      'GMD': 'D',
      'GNF': 'FG',
      'GTQ': 'Q',
      'GYD': '\$',
      'HKD': 'HK\$',
      'HNL': 'L',
      'HRK': 'kn',
      'HTG': 'G',
      'HUF': 'Ft',
      'IDR': 'Rp',
      'ILS': '₪',
      'IMP': '£',
      'INR': '₹',
      'IQD': 'ع.د',
      'IRR': '﷼',
      'ISK': 'kr',
      'JEP': '£',
      'JMD': 'J\$',
      'JOD': 'د.ا',
      'JPY': '¥',
      'KES': 'KSh',
      'KGS': 'с',
      'KHR': '៛',
      'KID': '\$',
      'KMF': 'CF',
      'KRW': '₩',
      'KWD': 'د.ك',
      'KYD': '\$',
      'KZT': '₸',
      'LAK': '₭',
      'LBP': 'ل.ل',
      'LKR': 'Rs',
      'LRD': '\$',
      'LSL': 'M',
      'LYD': 'ل.د',
      'MAD': 'د.م.',
      'MDL': 'L',
      'MGA': 'Ar',
      'MKD': 'ден',
      'MMK': 'Ks',
      'MNT': '₮',
      'MOP': 'MOP\$',
      'MRU': 'UM',
      'MUR': 'Rs',
      'MVR': 'Rf',
      'MWK': 'MK',
      'MXN': '\$',
      'MYR': 'RM',
      'MZN': 'MT',
      'NAD': '\$',
      'NGN': '₦',
      'NIO': 'C\$',
      'NOK': 'kr',
      'NPR': 'Rs',
      'NZD': '\$',
      'OMR': 'ر.ع.',
      'PAB': 'B/.',
      'PEN': 'S/',
      'PGK': 'K',
      'PHP': '₱',
      'PKR': 'Rs',
      'PLN': 'zł',
      'PYG': '₲',
      'QAR': 'ر.ق',
      'RON': 'lei',
      'RSD': 'дин',
      'RUB': '₽',
      'RWF': 'FRw',
      'SAR': 'ر.س',
      'SBD': '\$',
      'SCR': 'Rs',
      'SDG': 'ج.س.',
      'SEK': 'kr',
      'SGD': '\$',
      'SHP': '£',
      'SLL': 'Le',
      'SOS': 'S',
      'SRD': '\$',
      'SSP': '£',
      'STN': 'Db',
      'SYP': '£S',
      'SZL': 'L',
      'THB': '฿',
      'TJS': 'SM',
      'TMT': 'T',
      'TND': 'د.ت',
      'TOP': 'T\$',
      'TRY': '₺',
      'TTD': 'TT\$',
      'TVD': '\$',
      'TWD': 'NT\$',
      'TZS': 'TSh',
      'UAH': '₴',
      'UGX': 'USh',
      'USD': '\$',
      'UYU': '\$U',
      'UZS': 'лв',
      'VES': 'Bs',
      'VND': '₫',
      'VUV': 'VT',
      'WST': 'WS\$',
      'XAF': 'FCFA',
      'XCD': 'EC\$',
      'XDR': 'SDR',
      'XOF': 'CFA',
      'XPF': '₣',
      'YER': '﷼',
      'ZAR': 'R',
      'ZMW': 'ZK',
      'ZWD': 'Z\$'
    };
    return currencySymbols[upperCaseCurrencyCode] ?? '';
  }